##
## In this file, commented-out options are set to their default values in the comment. Options which
## are not commented out don't have default values.
##
## When setting up your own instance, please change or review all options which don't have a default
## value. Please also read all WARNINGs in this file. https://xkcd.com/293/
##

################
## Dropwizard ##
################

##
## Dropwizard magic so the REST API port can be configured
##
server:
  applicationConnectors:
    - type: http
      port: 9001 # REST API port
  adminConnectors:
    - type: http
      port: 9002 # Admin UI port
  requestLog:
    appenders:
      - type: console
        filterFactories:
          - type: metrics-endpoint

##
## Example log level configuration
##
## This example sets the global log level to WARN and VelCom's log level to INFO.
## Valid log levels are: DEBUG, INFO, WARN, ERROR
##
#logging:
#  level: WARN
#  loggers:
#    "de.aaaaaaah.velcom": INFO


#############
## General ##
#############

##
## The token by which the web administrator can authenticate
##
webAdminToken: "12345"

##
## The URL the benchmark repo should be cloned from
##
benchmarkRepoRemoteUrl: "https://github.com/IPDSnelting/velcom-unibench.git"

##
## The period in which the tracked repos and bench repo is checked for updates. When new commits are
## found, they are added to the queue.
##
#pollInterval: 120 # seconds


#################
## Directories ##
#################

##
## VelCom organizes its files into three different directories:
##
## - data/  : Essential files
## - cache/ : Non-essential files that persist between restarts
## - tmp/   : Short-lived temporary files
##
## Backups only need to include the config file and the data/ dir. With those files, VelCom can
## recreate the other two directories.
##
## WARNING: These directories belong to VelCom. VelCom will delete any files it doesn't recognize!
##
## WARNING: Files in these directories should not be changed or deleted while VelCom is running!
##
#dataDir: "data/"
#cacheDir: "cache/"
#tmpDir: "tmp/"


############
## Runner ##
############

##
## The token runners need to provide in order to connect successfully.
## Will be transmitted in plain text over an HTTPS connection.
##
runnerToken: "Correct-Horse_Battery Staple"

##
## The port that the dispatcher should be listening on
##
#runnerPort: 3546

##
## The duration in seconds after which disconnected runners are given up on (removed and commit
## rescheduled)
##
#disconnectedRunnerGracePeriodSeconds: 600


#########################
## Significant Commits ##
#########################

##
## A commit becomes significant if the following rules hold for at least one of its measurements and
## the corresponding measurement in the run of any parent commit:
##
## Rule 1: |(newValue - oldValue) / oldValue| >= significanceRelativeThreshold
## Rule 2: |newValue - oldValue| >= significanceStddevThreshold * stddev(newValues)
##
## If the amount of new values is below significanceMinStddevAmount, rule 2 doesn't apply.
##
#significanceRelativeThreshold: 0.05 # An increase or decrease by 5%
#significanceStddevThreshold: 2
#significanceMinStddevAmount: 25
