# Dropwizard magic so the REST API port can be configured
server:
  applicationConnectors:
    - type: http
      port: 9001 # REST API port
  adminConnectors:
    - type: http
      port: 9002 # Admin UI port
  requestLog:
    appenders:
      - type: console
        filterFactories:
          - type: metrics-endpoint

# The interval between listener updates. (in seconds)
pollInterval: 120

# The token for the web administrator
webAdminToken: "12345"

# The port that the dispatcher should be listening on
runnerPort: 3546

# The remote url where the benchmark repo remote url can be cloned from
benchmarkRepoRemoteUrl: "https://github.com/IPDSnelting/velcom-unibench.git"

# The token runners need to provide in order to connect successfully.
# Will be transmitted in plain text over an HTTPS connection.
runnerToken: "Correct-Horse_Battery Staple"

# The duration in seconds after which disconnected runners are given up on (removed and commit
# rescheduled)
disconnectedRunnerGracePeriodSeconds: 600

# A commit becomes significant if the following rules hold for at least one of its measurements and
# the corresponding measurement in the run of any parent commit:
#
# Rule 1: |(newValue - oldValue) / oldValue| >= significanceRelativeThreshold
# Rule 2: |newValue - oldValue| >= significanceStddevThreshold * stddev(newValues)
#
# If the amount of new values is below significanceMinStddevAmount, rule 2 doesn't apply.
significanceRelativeThreshold: 0.05 # An increase or decrease by 5%
significanceStddevThreshold: 2
significanceMinStddevAmount: 25

# The hashing algorithm's memory usage in KiB
hashMemory: 5120

# How many iterations the hashing algorithm should make. See the readme for more details on how to
# set this value.
hashIterations: 50
